### ISSUE TITLE
Multiple Flutter Engines Add-to-App Example

### ISSUE THREAD

**Issue by Lunacat78** [appium/appium-flutter-driver#259]
Like many others, I'm working on an app that is being converted from native iOS and Android apps to Flutter using the Add-to-App approach - however, with the [multiple Flutter engines approach](https://docs.flutter.dev/development/add-to-app/multiple-flutters).  Currently, as I'm trying to set this framework up, I am running into issues with connecting to the Appium server due to `main.dart` not being called until a Flutter specific screen is visited.

Does anyone have examples of this functionality in practice (potentially with the [multiple engines example provided by Flutter](https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters)) or can help guide me in the right direction with this?  I'm sure there are other applications out there that are using or will be using the framework in this use case.

**Comment by prolificcoder** [comment]
I was able to get sample iOS and Android add to apps running with ruby with [appium-userland/appium-flutter-driver](https://github.com/appium-userland/appium-flutter-driver)  

see: [iOS run for sample 2 app by prolificcoder](https://github.com/appium-userland/appium-flutter-driver/pull/256/files)  

But I am having problems with running it in our app: [Please reopen issue "ext.flutter.driver" is not found in "extensionRPCs" · Issue #258 · appium-userland/appium-flutter-driver](https://github.com/appium-userland/appium-flutter-driver/issues/258)

I think i am not sure where to add the `enableFlutterDriverExtension` in the main.dart since we have a module with main.dart and a package with main.dart. Though I tried both I wasn't able to get out of the extensionRPCs error. 

BTW can you share your logs, to verify if you are seeing similar errors.

**Comment by StephanB75** [comment]
@Lunacat78 have you found a solution for the multi engine approach ?
We have a legacy app which has 2 flutter modules (and engines), but the ext flutter driver connects only to one of them and i have no idea how to switch between the engines or how to solve this issue by a workaround

**Comment by KazuCocoa** [comment]
How about switching isolate as https://github.com/appium-userland/appium-flutter-driver#change-the-flutter-engine-attache-to ? (since appium flutter driver 1.3.0)

**Comment by KazuCocoa** [comment]
I wondered if https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#several-ways-to-start-an-application and the above comment help
