### ISSUE TITLE
Unable to takeScreenshot on failure using command driver.saveScreenshot()

### ISSUE THREAD

**Issue by kritika333** [appium/appium-flutter-driver#685]
I am trying to take screenshot on failure. Here is my code 

try{
await driver.execute('flutter:waitFor', elementtocheck,100);
console.log('Element displayed');
}
catch(error){
await driver.save screenshot('./error.png');
throw new Error('Element is not displaying');
}

For this code no screenshot is taken may be because execution is terminating and flutter app is closed and Its giving me output -  **Error: Function timed out , ensure the promise resolved within 50000 milliseconds.**  

But when I will use code 

try{
await driver.execute('flutter:waitFor', elementtocheck,100);
console.log('Element displayed');
}
catch(error){
throw new Error('Element is not displaying');
}. 

then on failure its giving me expected output as **Element is not displaying** and execution is terminating.

 How can I take screenshot on failure? any pointers ? Thank you.

**Comment by kritika333** [comment]
@KazuCocoa any pointers please ? Thank you

**Comment by KazuCocoa** [comment]
I haven't seen the behavior for screenshot, but I guess DartVM was not able to respond in the timeout because of the previous command was taking time (for example). To dig into the issue further, maybe reading DartVM/Flutter code would be needed.

As a workaround, the code could take screenshot via NATIVE_APP context. Then, it does not care about DartVM.

**Comment by KazuCocoa** [comment]
Alternatively, you could use native context's screenshot if Dart VM did not respond (as a workaround)
